# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# missing top-level class documentation comment が出ないように
Documentation:
  Enabled: false

# 複数行に渡ってメソッドチェーンを使う時のインデントはエンジニアに任せる
MultilineMethodCallIndentation:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/bundle
